### ISSUE TITLE
Amazon Voice Service Down?

### ISSUE THREAD

**Issue by BabackE** [alexa/alexa-avs-raspberry-pi#245]
The client has recently stopped working. Pressing the button I get a "Processing" message after I record a question but then no response from Alexa. The client was working perfectly on Thursday. Also saw that https://echosim.io/ is having the same issue.

Is voice service down? Anyone have any ETA for when it will be back up?

**Comment by hankp46** [comment]
Having same problem

**Comment by hankp46** [comment]
Having same problem. Log shows following message
statusCode == HttpStatus.NO_CONTENT_204) {
            log.info("This response successfully had no content.");

**Comment by olegberman** [comment]
Confirming the issue.

**Comment by ajotwani** [comment]
Don't have access to the Pi this weekend, but https://echosim.io
<https://echosim.io/welcome?next=%2F> seems to be up for me. Can anyone
confirm if that's working now?

**Comment by BabackE** [comment]
@ajotwani Just checked, I'm still not seeing it work, echosim.io also isn't working for me. Are you testing echosim on a desktop browser or mobile?

**Comment by rks0202** [comment]
It did worked for me on desktop/Firefox. tried 10 min before.

**Comment by BabackE** [comment]
I just got it working too, but I had to use my other Amazon login ID, the one I had been using for developing in this codebase doesn't seem to work on either echosim.io or the raspberry pi client.

**Comment by hankp46** [comment]
working this morning (8/8)

**Comment by olegberman** [comment]
@hankp46 Thanks, will check after work.

**Comment by Ztnepres** [comment]
Can confirm is working.
