### ISSUE TITLE
Nothing is happening after I press 'start listening'

### ISSUE THREAD

**Issue by sinfulangle** [alexa/alexa-avs-raspberry-pi#247]
When I press 'Start Listening' on the alexa voice service it seems like it recognises my voice but it isn't saying anything back.

![image](https://cloud.githubusercontent.com/assets/20607239/17462068/f1ebcc14-5ce3-11e6-9fc7-17d8c3f820bc.png)

![image](https://cloud.githubusercontent.com/assets/20607239/17462072/11035752-5ce4-11e6-88be-22419c39d2b5.png)

Looks like no errors or anything appeared after running the commands

**Comment by olegberman** [comment]
Confirming the issue.

**Comment by yornstei** [comment]
I have the same issue. 

No problem throughout the steps, servers running well, program opens with no errors, however when I click 'Start listening' I hear the prompt to speak, seems like its listening, after clicking 'Stop listening' I see the 'processing' but when that's done I don't here the output! (yes my speaker is working, I hear the prompt to start and stop talking). 

Both my terminal server tab and javaclient tab show the same log as @sinfulangle.

??

**Comment by sinfulangle** [comment]
Very strange olegberman/yornstei.

awaiting a fix.

**Comment by hankp46** [comment]
I had same problem but it started working again this morning (8/8)

**Comment by yornstei** [comment]
Same here, it started working for me without any changes.

(only thing I may have changed, though I think I changed it before coming up with the issue above, was running 'npm start' in 'sudo'. I saw on another thread not running in sudo may cause 'not found' errors that I had earlier)

No issues by me. good luck.

**Comment by Ztnepres** [comment]
can confirm. my old pi setup that wasn't working is now working today.

**Comment by hglynn** [comment]
I'm having this problem too. Reasonably clean install, I know my USB headset is working; no console errors, I can see the mic bar jumping about when I talk, but when i stop listening, nothing happens, no Alexa etc. Any further thoughts on this one?

**Comment by ajotwani** [comment]
@hglynn you still having issues with this?

**Comment by olegberman** [comment]
It looks like it was Amazon's server problem. Not happening anymore

**Comment by ajotwani** [comment]
We're closing this Issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if this is an error, let us know with a comment and we'll be happy to reopen the Issue.

Thanks!
