### ISSUE TITLE
Headphones and Microphone on 3.5 mm port

### ISSUE THREAD

**Issue by anujdutt9** [alexa/alexa-avs-raspberry-pi#251]
Hi. I have my headphones with microphone in-built and can connect to raspberry pi via 3.5 mm port. According to the documentation, the interface expects the microphone input from the USB port and output from the speaker connected to 3.5 mm port.
Can you please guide me or tell the changes that I need to make to test Alexa with both microphone and speaker connected to 3.5 mm port.
Thanks : )

**Comment by animeshp** [comment]
I've have the same issue. Any help is appreciated :)

**Comment by blaineoliver** [comment]
note how your phone or any other device has 4 segments to their jack input and standard 3.5mm has 3 segments, that missing segment is for microphone. You won't be able to use this like this for the raspberry pi.

**Comment by somu1795** [comment]
Pi has 3 segments on the 3.5 mm jack - 2 for audio and 1 for video, so no , you cannot connect a microphone through port.
