### ISSUE TITLE
Alexa without "start listening" button?

### ISSUE THREAD

**Issue by DongNguyenPhuc** [alexa/alexa-avs-raspberry-pi#257]
hi folks I'm working on this. Can anyone please show me how can i automatically wake my raspberry up from anywhere in the room with keywords such as "Alexa" or "Raspberry"...without pressing "Start listening" button? I'm just a student so I hope you guys can help me through. I will be very appreciated. Thanks

**Comment by yeralin** [comment]
Probably we will need edit some java code. Will try to fork it, and make it work w/o UI and npm server

**Comment by yeralin** [comment]
Ok, take a look at this discussion: https://github.com/alexa/alexa-avs-raspberry-pi/issues/4

Can be closed now.

**Comment by ajotwani** [comment]
Closing.

**Comment by jameslo627** [comment]
Is there any sample without pressing "Start listening" for Windows 10?
